### ISSUE TITLE
Request to automate R script in pbix

### ISSUE THREAD

**Issue by varunbeesu** [dubravcik/pbixrefresher-python#1]
Great work by dubravcik, working perfectly for me. Thank you very much for your contribution. 

I have another request regarding R-script. I have to refresh daily pbix file and run R-script manually as I am unable to run r-script at published place automatically. Is it possible to run R-script after refreshing pbix file from your script? Thanks in advance

**Comment by Broadtree** [comment]
Oh, I'm not having the same joy. The reason isn't your solution more that I've no experience with Python, so struggling a bit there.

**Comment by dubravcik** [comment]
Hi @varunbeesu, I tried to add a simple R-script to my dashboard and it worked for me - the R script was executed automatically when Power BI opened. As I am not an R user, maybe it doesn't work like that in all cases. 
I am not sure how should I update the solution to have R-script refreshed in general. Can you maybe describe how do you refresh it manually? If you attach sample notebook, it would be helpful.
Thanks
