### ISSUE TITLE
Changes done as per the need like timeout and others but not reflecting into .exe file

### ISSUE THREAD

**Issue by furqanubm** [dubravcik/pbixrefresher-python#19]
I have done some of the changes done as per the need like timeout and others but not reflecting into .exe file Below is the sample. 

****I just need to re-compile this exe, so the changes will reflect into exe file, could you please help me to do this****

	time.sleep(30)

orig_stdout = sys.stdout
f = open('out.txt', 'w')
sys.stdout = f

	print("Starting Power BI changes")
	os.system('start "" "' + WORKBOOK + '"')
	time.sleep(INIT_WAIT)

	print("Identifying Power BI window")
	app = Application(backend = 'uia').connect(path = PROCNAME)
	win = app.window(t

**Comment by dubravcik** [comment]
Hi @furqanubm , after you edited the file you can install the package locally to create the binary exe file.
```
cd /pathToPbixrefresherFolder
pip install -e .
```

Read more at https://packaging.python.org/tutorials/installing-packages/

Or you can execute the edited .py file directly
```
python pbixrefresher/pbixrefresher.py sample.pbix
```
