### ISSUE TITLE
Bypass first time PowerBI Desktop screen

### ISSUE THREAD

**Issue by masters3d** [dubravcik/pbixrefresher-python#2]
I want to run this script off a VM. Power Bi desktop shows a first time screen that can not be dismissed unless you provide it some information. Since the VM gets destroyed after this run, I am not able to save the state. Any ideas on how to bypass this screen? Currently the script just times out. Thanks

![capture-small](https://user-images.githubusercontent.com/6539412/34233611-4449ab84-e59b-11e7-87d0-b73a457e0540.jpg)

**Comment by masters3d** [comment]
I just found the answer: https://docs.microsoft.com/en-us/power-bi/desktop-admin-sign-in-form

**Comment by masters3d** [comment]
```
REG ADD "HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Power BI Desktop" /v ShowLeadGenDialog /t REG_DWORD /d 0 /f
```

**Comment by dubravcik** [comment]
Yep, currently the script requires first-time manual configuration  i.e. sign in, uncheck startup screen. So it is not good for an automatically built environment from scratch right now as you have.
@masters3d I am wondering if it works correctly for you after you had set the registry to disable sign-in form. You still need to sign in somehow to be able to publish it, don't you?

Thanks
Michal

**Comment by masters3d** [comment]
It works.  I disabled the publishing feature of the script as I am using another script to do the uploading.
