### ISSUE TITLE
Element Ambiguous Error when publishing

### ISSUE THREAD

**Issue by MiConnell** [dubravcik/pbixrefresher-python#26]
Power BI Version: 2.75.5649.861 64-bit (November 2019)
Windows 10

When getting to publishing, there's an elementambiguouserror with pywinauto that show two Publish to Power BI options.

Error and screenshot below. 

pywinauto.findwindows.ElementAmbiguousError: There are 2 elements that match the criteria {'title': 'My workspace', 'top_level_only': False, 'parent': <uia_element_info.UIAElementInfo - 'Publish to Power BI', WindowsForms10.Window.20008.app.0.3c73ab4_r6_ad1, 988888>, 'backend': 'uia'}

![image](https://user-images.githubusercontent.com/14168559/69744888-e5ffcd00-10f5-11ea-914c-d5deb95727ed.png)

**Comment by jorisguichard** [comment]
I have the exact same issue here... 

![image](https://user-images.githubusercontent.com/50142821/70151235-97c96b80-16ab-11ea-8f8a-7b658cfa1352.png)

**Comment by jorisguichard** [comment]
I think this can be fixed by adding 'found_index = 0' to line 77:

![image](https://user-images.githubusercontent.com/50142821/70156756-bbdd7a80-16b4-11ea-9c64-c005e0102ace.png)

**Comment by MiConnell** [comment]
That worked, thanks!
