### ISSUE TITLE
Trouble with Task Scheduler

### ISSUE THREAD

**Issue by andre-msousa** [dubravcik/pbixrefresher-python#6]
Hey man, first of all, congratulations for this solution.

I'm trying to used it on a server, with the Task Scheduler of Windows.
Works  pretty well when I'm logged on, but every time it running trough the Task Scheduller, without a user logged, I get an error.

How was the solution you found to automate this process?

Thanks in advance.

**Comment by AlexeyPrishchepo** [comment]
Thanks for the great solution! The same trouble here: when my desktop is password locked, the script returns error. Is there any workaround for this?

**Comment by AlexeyPrishchepo** [comment]
I guess this is because pywinauto cannot accuire GUI context when not logged in or when desktop is locked. [Here](https://stackoverflow.com/questions/47137372/how-to-restore-a-window-in-rdp-using-pywinauto-when-rdp-is-in-minimized-state) are some workarounds but I didn't try them yet. Let us know if you find a solution.

**Comment by Dppprasad** [comment]
@AlexeyPrishchepo & @andre-msousa 

Hey Guys, I have the same issue. Did you guys find a way around it? Thank you

**Comment by AlexeyPrishchepo** [comment]
Hey,
I finally gave up looking for workarounds and installed and configured on-premises data gateway in personal mode and it worked. Had some troubles with date columns and so on but successfully resolved them with ms support.

**Comment by dubravcik** [comment]
I have added steps how to schedule it in Task scheduler into readme https://github.com/dubravcik/pbixrefresher-python/blob/master/README.md
btw user has to be logged in, it doesn't work without it as it needs active GUI in Windows.
