### ISSUE TITLE
Publish is back on y01y27 in the March 2018 version

### ISSUE THREAD

**Issue by ImkeF** [dubravcik/pbixrefresher-python#8]
In the current version (Version: 2.56.5023.1021 64-bit (March 2018) the publish-button is back on: y27 (instead of y25).

**Comment by dubravcik** [comment]
Thanks for comment. Moreover all preview feature buttons are changing the anchor number.
I have to change the method how to call PBI functionality.
Thanks

**Comment by dubravcik** [comment]
I changed button identification to use the name of the button i.e. Refresh or Publish. Done in 0.1.15
