### ISSUE TITLE
Not recognized as command

### ISSUE THREAD

**Issue by youngkrs** [dubravcik/pbixrefresher-python#9]
After successful install, I can't get the package to launch. I'm assuming it has something to do with the path variable but not sure. I'm more on the data science side vs programming side, so apologies if this is an issue not related to the package. 

Put project directory on my desktop
C:\Users\computer_name\Desktop\pbixrefresher-python-master>pbixrefresher sample.pbix

'pbixrefresher' is not recognized as an internal or external command,
operable program or batch file.

![picture1](https://user-images.githubusercontent.com/11018284/38443827-9bffdf54-39b2-11e8-9e7f-f10f14e35f06.png)
![picture2](https://user-images.githubusercontent.com/11018284/38443828-9c0f9b24-39b2-11e8-8584-686568dbf668.png)

**Comment by dubravcik** [comment]
Hi @youngkrs, thanks for feedback. I have changed  `entry_points` in pip setup and it should work. Please try latest version from pip.
Thanks

**Comment by youngkrs** [comment]
Thanks, the changes you made worked. Thanks so much for your help!!
